#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

cd /folder/with/vpn/profiles
unset options i
while IFS= read -r -d $'\0' f; do
  options[i++]="$f"
done < <(find -type f -name "*.ovpn" -print0 )

select vpn in "${options[@]}" "Exit"; do
  case $vpn in
    *.ovpn)
      echo "Connecting to $vpn"
      openvpn $vpn > /dev/null &
      break
      ;;
    "Exit")
      break
      ;;
    *)
      echo "¿?"
      ;;
  esac
done
